### PR TITLE
[x11-misc/polybar] Bump version to 3.0.3

### LINKED ISSUE #14: Polybar 3.0.2 has rendering problems, please update to 3.0.3
That's it. Here's the [issue](https://github.com/jaagr/polybar/issues/389).

Please, update ASAP.

### PR DESCRIPTION
**Pull request by bpinto**
- Code to support check debug check.
- Fix incorrectly named IPC cmake argument.

Fixes #14 
Reference: https://github.com/jaagr/polybar/commit/41f7f82bd0c48d5893195060291498be848ed3f5

### CODE REVIEW

**Comment by bpinto** [comment]
@Vintodrimmer the problem I am having with this version is that when I restart my computer, the bar is not present. I haven't debugged it yet.

**Comment by bpinto** [comment]
I found the [bug](https://github.com/jaagr/polybar/issues/399), I'm not sure if this bug was introduced on 3.0.3 or if it is already present on 3.0.2. But as @jaagr is active on the project, I suspect this is going to be fixed very soon.

**Comment by Dr-Terrible** [comment]
LGTM :+1:

**Comment by Vintodrimmer** [comment]
Thanks.

Can you have some older version present in overlay while you work on the current ones?

2.5.something was working great.

**Comment by Dr-Terrible** [comment]
> Can you have some older version present in overlay while you work on the current ones?

I'm having issues with 3.0.3 too; sometime polybar segments randomly, so I think it's a good idea to keep around the ebuild of the old 2.5.2 as a fallback in case of problems.

@bpinto what do you think? Maybe, we should skip 3.0.3 entirely and package the snapshot with the fix from jaagr: https://github.com/jaagr/polybar/commit/6fa2d3943cc9e2bd36895c58f93bfd8b49dfec66

**Comment by bpinto** [comment]
@Dr-Terrible What about masking the 3.x release for now and just including the 2.5.2 as the stable version?

We could patch the 3.0.3 release sure, but your bug seem to describe another issue and given he releases things quite often I would rather not apply any non-upstream patch.

Also, correct me if I'm wrong, but couldn't we install from git with the current ebuild? Or do we need to create a `-9999` ebuild?

**Comment by bpinto** [comment]
@Dr-Terrible I have added the older version without any masking. Let me know what you prefer.

**Comment by Dr-Terrible** [comment]
> What about masking the 3.x release for now and just including the 2.5.2 as the stable version?

SGTM :+1: 

> Also, correct me if I'm wrong, but couldn't we install from git (which includes the fix) with the current ebuild? Or do we need to create a -9999 ebuild?

I'm not sure I'm understanding your question, but you can get a tarball from a specific GitHub's hash, as I have done for LWAN: https://github.com/Dr-Terrible/ineluctable-overlay/blob/master/www-servers/lwan/lwan-0.1.0_pre20170131.ebuild  That way you don't need to relay on -9999 ebuilds or use git eclass at all. `6fa2d39` will become `polybar-3.0.4_beta1.ebuild` (or whatever scheme number you prefer, I'm fine with `polybar-3.0.3.ebuild`  too; I have no specific preference).

> Update: My idea is not to run a masked version for long, so I'd probably unmask it once 3.0.4 hits upstream or so and then later on leave both 2.5.2 and 3.0.x as stable and remove 2.5.2 once 3.1 is released

I agree with your plan. Waiting until 3.1 seems a good compromise :)

**Comment by bpinto** [comment]
@Dr-Terrible I have just realized that we were not marking those builds as stable! :sweat_smile: 

I have pushed the latest, which I think will fix CI as well, review when you can!

**Comment by Dr-Terrible** [comment]
@bpinto at the moment `jsoncpp` is quite a mess, see: https://bugs.gentoo.org/show_bug.cgi?id=593074  and the stabilisation process of jsoncpp-1.8.0 is lagging behind: https://bugs.gentoo.org/show_bug.cgi?id=601204  For that reason, polybar-2.5.2 will never satisfy repoman, leading to Travic's complains. What if we hard mask polybar-3.0.x and mark polybar-2.5.2 as unstable until the 3.1 release is ready?

**Comment by bpinto** [comment]
I don't know what hard mask means, sorry! Could you tell me more about it?

**Comment by Dr-Terrible** [comment]
@bpinto an hard mask is enabled when you put an entry in `profiles/package.mask`. I suggest to add =x11-misc/polybar-3.0* as a temporary workaround until the conflict of polybar-2.5 with json-1.8 is resolved.

**Comment by bpinto** [comment]
@Dr-Terrible I have pushed yet another code :D... let's see what Travis think about it!

**Comment by Dr-Terrible** [comment]
awesome, @bpinto great job :)

**Comment by bpinto** [comment]
Thanks for the guidance!

**Comment by Vintodrimmer** [comment]
Hey guys, thanks for the 3.0.3 and 2.5.2. Both work great for me.

I have a question, but I'm net sure that this is the right place to ask it.

Builds (2.5.2; 3.0.2; 3.0.3) fail for me if I select "xrender" USE-flag with the following errors:

```
/tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/src/x11/connection.cpp: In constructor ‘polybar::v2_0_0::connection::connection(xcb_connection_t*, int)’:
/tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/src/x11/connection.cpp:45:3: error: ‘render_util’ has not been declared
   render_util::query_extension(*this);
   ^~~~~~~~~~~
[ 85%] Building CXX object bin/CMakeFiles/polybar.dir/x11/extensions/randr.cpp.o
cd /tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3_build/bin && /usr/bin/x86_64-pc-linux-gnu-g++   -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/alsa -I/tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/include -I/tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/lib/concurrentqueue/include -I/tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/lib/xpp/include   -DNDEBUG -march=native -O3 -pipe -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors   -pthread -std=c++14 -o CMakeFiles/polybar.dir/x11/extensions/randr.cpp.o -c /tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/src/x11/extensions/randr.cpp
make[2]: *** [bin/CMakeFiles/polybar.dir/build.make:1479: bin/CMakeFiles/polybar.dir/x11/connection.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/src/x11/extensions/composite.cpp: In function ‘void polybar::v2_0_0::composite_util::query_extension(polybar::v2_0_0::connection&)’:
/tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/src/x11/extensions/composite.cpp:12:10: error: request for member ‘composite’ is ambiguous
     conn.composite().query_version(XCB_COMPOSITE_MAJOR_VERSION, XCB_COMPOSITE_MINOR_VERSION);
          ^~~~~~~~~
In file included from /tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/include/x11/extensions/composite.hpp:10:0,
                 from /tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/src/x11/extensions/composite.cpp:1:
/tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/lib/xpp/include/xpp/proto/composite.hpp:351:5: note: candidates are: const xpp::composite::interface<Derived, Connection>& xpp::composite::interface<Derived, Connection>::composite() [with Derived = polybar::v2_0_0::detail::interfaces<polybar::v2_0_0::detail::connection_base<polybar::v2_0_0::connection&, xpp::randr::extension, xpp::render::extension, xpp::sync::extension, xpp::composite::extension, xpp::xkb::extension>, xpp::randr::extension, xpp::render::extension, xpp::sync::extension, xpp::composite::extension, xpp::xkb::extension>; Connection = polybar::v2_0_0::detail::connection_base<polybar::v2_0_0::connection&, xpp::randr::extension, xpp::render::extension, xpp::sync::extension, xpp::composite::extension, xpp::xkb::extension>]
     composite(void)
     ^~~~~~~~~
In file included from /tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/include/x11/extensions/render.hpp:10:0,
                 from /tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/include/x11/extensions/all.hpp:9,
                 from /tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/include/x11/connection.hpp:11,
                 from /tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/src/x11/extensions/composite.cpp:3:
/tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3/lib/xpp/include/xpp/proto/render.hpp:1983:5: note:                 template<class ... Parameter> void xpp::render::interface<Derived, Connection>::composite(Parameter&& ...) const [with Parameter = {Parameter ...}; Derived = polybar::v2_0_0::detail::interfaces<polybar::v2_0_0::detail::connection_base<polybar::v2_0_0::connection&, xpp::randr::extension, xpp::render::extension, xpp::sync::extension, xpp::composite::extension, xpp::xkb::extension>, xpp::randr::extension, xpp::render::extension, xpp::sync::extension, xpp::composite::extension, xpp::xkb::extension>; Connection = polybar::v2_0_0::detail::connection_base<polybar::v2_0_0::connection&, xpp::randr::extension, xpp::render::extension, xpp::sync::extension, xpp::composite::extension, xpp::xkb::extension>]
     composite(Parameter && ... parameter) const
     ^~~~~~~~~
make[2]: *** [bin/CMakeFiles/polybar.dir/build.make:1527: bin/CMakeFiles/polybar.dir/x11/extensions/composite.cpp.o] Error 1
make[2]: Leaving directory '/tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3_build'
make[1]: *** [CMakeFiles/Makefile2:457: bin/CMakeFiles/polybar.dir/all] Error 2
make[1]: Leaving directory '/tmp/portage/x11-misc/polybar-3.0.3/work/polybar-3.0.3_build'
make: *** [Makefile:128: all] Error 2

```

Is that a problem on my part or does it also happen to you?

**Comment by bpinto** [comment]
I have the same problem, maybe it's a lack of dependency. I have never installed it with this use flag before.

**Comment by Dr-Terrible** [comment]
> Builds (2.5.2; 3.0.2; 3.0.3) fail for me if I select "xrender" USE-flag with the following errors:

I'll give a look later, meanwhile can you pastebin somewheree the output of these command?

```shell
$ emerge --info
$ emerge -1pv --nodeps polybar
```

**Comment by Vintodrimmer** [comment]
Sorry, should have done that in the first place.
Guess there is no need for them anymore. Just didn't want to be rude and not reply.

**Comment by Dr-Terrible** [comment]
Don't worry @Vintodrimmer. We are cool :)

**Pull request merged**
