### PR TITLE
[x11-misc/polybar] Version bump to 2.4.3

### PR DESCRIPTION
**Pull request by bpinto**
Introduces CURL and WIFI USE flags.

### CODE REVIEW

**Comment by bpinto** [comment]
I'm testing this new build. What do you think about the changes?

**Comment by Dr-Terrible** [comment]
Hi @bpinto. Thank you for the PR.

> I'm testing this new build. What do you think about the changes?

Looks good to me, except I3IPCPP_ECOMMIT.

You need to update the hash commit for I3IPCPP (8ed7831) too; see here for a reference: https://github.com/jaagr/polybar/tree/068d5867576ad7209da8945dcb68f57cf13d9fe5/lib

**Comment by bpinto** [comment]
Oh I see, thanks for the reference link.

I have updated the files to include this newer module.

**Comment by Dr-Terrible** [comment]
All good! Merging.

**Pull request merged**
